/**
 * Capacitor native shell config (ADR 0017). The mobile app is the `vite build`
 * output loaded into a WebView — assets are bundled and the app runs offline;
 * no `server` block is ever committed (ADR 0017 §3).
 *
 * The native projects (`ios/`, `android/`) are generated by `npx cap add`,
 * which is human-gated (ADR 0017 §6) — see README.md.
 */
import type { CapacitorConfig } from '@capacitor/cli'

const config: CapacitorConfig = {
  appId: 'com.homeofed.espy',
  appName: 'Espy',
  webDir: 'dist',
  plugins: {
    // Page chrome is --espy-paper (tokens.scss), not the canvas-card cream.
    StatusBar: {
      style: 'LIGHT', // light background → dark content
      backgroundColor: '#f7efdc',
    },
    SplashScreen: {
      backgroundColor: '#f7efdc',
      launchAutoHide: true,
    },
  },
}

export default config
